### PR TITLE
Decode extrinsic errors

### LINKED ISSUE #160: cli should return readable extrinsic erros
currently, we get errors like
```
[2022-02-12T20:50:30Z ERROR encointer_client_notee] ExtrinsicFailed: Module(ModuleError { index: 10, error: 18, message: None }) DispatchInfo { weight: 10000, class: DispatchClass::Normal, pays_fee: Pays::Yes }
```
we should properly decode these errors

### PR DESCRIPTION
**Pull request by pifragile**
* Closes #160

### CODE REVIEW

File: client/src/main.rs [hunk 1]
```diff
@@ -1405,10 +1405,17 @@ fn listen(matches: &ArgMatches<'_>) {
...
 							frame_system::Event::ExtrinsicFailed {
-								dispatch_error,
-								dispatch_info,
+								dispatch_error: _,
+								dispatch_info: _,
 							} => {
-								error!("ExtrinsicFailed: {:?} {:?}", dispatch_error, dispatch_info);
+								let ed = EventsDecoder::new(api.clone().metadata);
+								let mut v = Vec::<frame_system::EventRecord<Event, Hash>>::new();
+								v.push(evr.clone());
```
Comment (clangenb) [inline client/src/main.rs]: I guess you can ommit the clone

**Review by clangenb — COMMENTED** [review]
Haven't tested it, but it looks good to me!

**Comment by clangenb** [comment]
Nice: I can confirm that it works!

Excerpt from `./bot-community.py test`

```bash
[encointer_client_notee] ExtrinsicFailed: (ApplyExtrinsic(10), Error(Module(PalletError { pallet: "EncointerCeremonies", error: "ParticipantIsNotRegistered", description: ["Participant is not registered"] })))
```

File: client/src/main.rs [hunk 2]
```diff
@@ -1460,10 +1460,17 @@ fn listen(matches: &ArgMatches<'_>) {
...
 							} => {
-								error!("ExtrinsicFailed: {:?} {:?}", dispatch_error, dispatch_info);
+								let ed = EventsDecoder::new(api.metadata.clone());
+								let event_records = vec![evr];
+
+								let decoded_event = &ed
+									.decode_events(&mut event_records.encode().as_slice())
+									.unwrap()[0];
+
+								error!("ExtrinsicFailed: {:?}", decoded_event);
```
Comment (clangenb) [inline client/src/main.rs:1473]: Very cool! I think this was not that easy to find out how it works, I am impressed!

Sorry, for making slight readability adjudments here. :)

**Review by clangenb — APPROVED** [review]
