### PR TITLE
cli refactoring and breaking renames

### LINKED ISSUE #423: [cli] Refactoring Clap Upgrade & Subcommand Restructuring
This will be a breaking change!
## Current State

- **Clap version**: Uses `clap` + `clap_nested` (pre-3.x builder pattern)
- **CLI style**: Flat list of ~80+ subcommands registered via `.add_cmd()` chains on a `Commander`
- **Argument handling**: Custom `EncointerArgs` / `EncointerArgsExtractor` traits wrapping `ArgMatches`
- **Commands**: 14 command modules in `src/commands/`, each exporting async handler functions
- **Shared state**: Node URL, port, CID extracted from `ArgMatches` via trait methods

## Target State (modeled after Integritee CLI pattern)

- **Clap version**: `4.5.x` with `derive` feature
- **CLI style**: Derive-based `#[derive(Parser)]` structs and `#[derive(Subcommand)]` enums
- **Argument handling**: Typed struct fields with clap attributes replace string-keyed `ArgMatches`
- **Commands**: Grouped into subcommand categories with two-level dispatch
- **Shared state**: Global `Cli` struct passed by reference to all command handlers

---

#### 1. Update `Cargo.toml`
- Replace `clap` and `clap_nested` dependencies with `clap = { version = "4.5", features = ["derive"] }`
- Remove `clap_nested` entirely
- Add `thiserror` for structured error types (if not present)

#### 2. Define result/error types (`src/error.rs`)
- Create `CliError` enum with `#[derive(Debug, thiserror::Error)]`
- Variants: `Extrinsic`, `ApiConnection`, `KeystoreError`, `ParseError`, `IoError`, etc.
- Define `pub type CliResult = Result<CliResultOk, CliError>;`
- Define `CliResultOk` enum if commands need to return typed data, or use `()` if all output is printed directly

#### 3. Create main `Cli` struct (`src/lib.rs` or `src/cli.rs`)
```rust
#[derive(Parser)]
#[command(name = "encointer-client-notee")]
#[command(version, author, about)]
pub struct Cli {
    /// Substrate node WebSocket URL
    #[arg(short = 'u', long, default_value = "ws://127.0.0.1")]
    pub node_url: String,

    /// Substrate node WebSocket port
    #[arg(short = 'p', long, default_value = "9944")]
    pub node_port: String,

    /// Community identifier (optional, required by most community commands)
    #[arg(long)]
    pub cid: Option<String>,

    #[command(subcommand)]
    pub command: Commands,
}
```

#### 4. Define `Commands` enum (`src/commands/mod.rs`)

Group the ~80 flat subcommands into logical categories:

```rust
#[derive(Subcommand)]
pub enum Commands {
    // Flatten keystore commands to top level (frequently used)
    #[command(flatten)]
    Account(AccountCommand),

    /// Community management
    #[command(subcommand)]
    Community(CommunityCommand),

    /// Ceremony participation and management
    #[command(subcommand)]
    Ceremony(CeremonyCommand),

    /// Scheduler phase queries and control
    #[command(subcommand)]
    Scheduler(SchedulerCommand),

    /// Bazaar marketplace
    #[command(subcommand)]
    Bazaar(BazaarCommand),

    /// Faucet management
    #[command(subcommand)]
    Faucet(FaucetCommand),

    /// Reputation rings (ring-VRF personhood proofs)
    #[command(subcommand)]
    Reputation(ReputationCommand),

    /// Democracy / governance proposals
    #[command(subcommand)]
    Democracy(DemocracyCommand),

    /// Offline payment (ZK proofs)
    #[command(subcommand)]
    OfflinePayment(OfflinePaymentCommand),

    /// Core chain operations (balance, transfer, etc.)
    #[command(flatten)]
    Chain(ChainCommand),
}
```

**Grouping rationale:**

| Group | Current commands | UX |
|-------|-----------------|-----|
| `Account` (flattened) | `new-account`, `list-accounts`, `export-secret` | `cli new-account` |
| `Chain` (flattened) | `balance`, `transfer`, `transfer-all`, `listen`, `print-metadata` | `cli balance ...` |
| `Community` | `new-community`, `add-locations`, `remove-location`, `list-communities`, `list-locations` | `cli community list` |
| `Ceremony` | 16 ceremony commands | `cli ceremony register ...` |
| `Scheduler` | `get-phase`, `get-cindex`, `next-phase` | `cli scheduler get-phase` |
| `Bazaar` | 6 bazaar commands | `cli bazaar list-businesses` |
| `Faucet` | 6 faucet commands | `cli faucet create ...` |
| `Reputation` | 6 ring commands + 2 commitment commands | `cli reputation get-rings` |
| `Democracy` | 8 governance commands | `cli democracy vote ...` |
| `OfflinePayment` | 13 offline payment commands | `cli offline-payment generate ...` |

The `#[command(flatten)]` on `Account` and `Chain` keeps the most common operations at the top level (no extra subcommand word needed).

#### 5. For each command group, create a subcommand enum in its module

Example for `CeremonyCommand` (`src/commands/ceremonies.rs`):

```rust
#[derive(Subcommand)]
pub enum CeremonyCommand {
    /// Register as participant for next ceremony
    Register {
        #[arg(long)]
        account: String,
        // ...
    },
    /// Upgrade registration (e.g., from newbie to reputable)
    UpgradeRegistration { /* ... */ },
    /// Unregister from ceremony
    Unregister { /* ... */ },
    /// Endorse newcomers (bootstrapper only)
    EndorseNewcomers { /* ... */ },
    /// Attest attendees after meetup
    AttestAttendees { /* ... */ },
    /// Claim ceremony reward
    ClaimReward { /* ... */ },
    /// List registered participants
    ListParticipants,
    /// List meetup assignments
    ListMeetups,
    /// Print ceremony statistics
    Stats,
    // ... etc
}
```

Each variant's fields replace the old ad-hoc `.arg()` definitions with typed, documented struct fields.

#### 6. Implement `run()` on each command group

```rust
impl CeremonyCommand {
    pub async fn run(&self, cli: &Cli) -> CliResult {
        match self {
            Self::Register { account, .. } => { /* logic */ },
            Self::ListParticipants => { /* logic */ },
            // ...
        }
    }
}
```

#### 7. Replace `EncointerArgs` / `EncointerArgsExtractor` traits

- These traits added arguments to `App` and extracted values from `ArgMatches` by string key
- With derive-based clap, struct fields handle both definition and extraction
- **Delete** `src/cli_args.rs` entirely
- Move any shared argument groups into reusable clap `Args` structs:

```rust
#[derive(Args)]
pub struct AccountArgs {
    /// Account address or name from keystore
    #[arg(long)]
    pub account: String,
}

#[derive(Args)]
pub struct SeedArgs {
    /// Secret seed for signing
    #[arg(long)]
    pub seed: Option<String>,
}
```

- Embed these as fields in command variants that need them (composition over string keys)

#### 8. Refactor `utils.rs`

- Change `get_chain_api()` to accept `&Cli` instead of `&ArgMatches`
- Change `xt()`, `sudo_call()`, `batch_call()` to accept typed parameters
- Update `ensure_payment()` and send helpers similarly
- The `CallWrapping` enum and governance helpers remain largely the same

#### 9. Migrate each command module (one module at a time, in this order to manage complexity)

| Order | Module | Complexity | Notes |
|-------|--------|-----------|-------|
| 1 | `keystore.rs` → `account.rs` | Low (3 cmds) | Good warm-up, no chain calls |
| 2 | `frame.rs` → merge into `chain.rs` | Low (1 cmd) | Treasury query |
| 3 | `encointer_scheduler.rs` → `scheduler.rs` | Low (3 cmds) | Simple queries |
| 4 | `encointer_core.rs` → `chain.rs` | Medium (5 cmds) | Balance, transfer, listen |
| 5 | `encointer_communities.rs` → `community.rs` | Medium (5 cmds) | Uses `CommunitySpec` |
| 6 | `encointer_bazaar.rs` → `bazaar.rs` | Medium (6 cmds) | Straightforward |
| 7 | `encointer_faucet.rs` → `faucet.rs` | Medium (6 cmds) | Mix of user/governance calls |
| 8 | `encointer_reputation_commitments.rs` → merge into `reputation.rs` | Low (2 cmds) | |
| 9 | `encointer_reputation_rings.rs` → `reputation.rs` | Medium (6 cmds) | Ring-VRF crypto |
| 10 | `encointer_democracy.rs` → `democracy.rs` | Medium (8 cmds) | Governance |
| 11 | `encointer_ceremonies.rs` → `ceremonies.rs` | High (16 cmds) | Largest module |
| 12 | `encointer_offline_payment.rs` → `offline_payment.rs` | High (13 cmds) | ZK proof handling |
| 13 | `encointer_ipfs.rs` → `ipfs.rs` or merge into `community.rs` | Low (1 cmd) | |
| 14 | `encointer_treasuries.rs` → merge into `chain.rs` | Low (1 cmd) | |

**Migration pattern for each module:**
- Define subcommand enum variants with typed fields
- Move handler function bodies into `match` arms of `run()`
- Replace `matches.value_of("arg_name")` with direct struct field access
- Replace `get_chain_api(matches)` with `get_chain_api(cli)`
- Delete old function signatures

#### 10. Simplify `main.rs`

```rust
use clap::Parser;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    env_logger::init();
    let cli = Cli::parse();
    commands::match_command(&cli).await?;
    Ok(())
}
```

#### 11. Create top-level dispatcher (`src/commands/mod.rs`)

```rust
pub async fn match_command(cli: &Cli) -> CliResult {
    match &cli.command {
        Commands::Account(cmd) => cmd.run(cli).await,
        Commands::Chain(cmd) => cmd.run(cli).await,
        Commands::Community(cmd) => cmd.run(cli).await,
        Commands::Ceremony(cmd) => cmd.run(cli).await,
        Commands::Scheduler(cmd) => cmd.run(cli).await,
        Commands::Bazaar(cmd) => cmd.run(cli).await,
        Commands::Faucet(cmd) => cmd.run(cli).await,
        Commands::Reputation(cmd) => cmd.run(cli).await,
        Commands::Democracy(cmd) => cmd.run(cli).await,
        Commands::OfflinePayment(cmd) => cmd.run(cli).await,
    }
}
```

#### 12. Delete removed files
- `src/cli_args.rs` (replaced by derive structs)
- Remove `clap_nested` from `Cargo.toml`

#### 13. Update `community_spec.rs`
- Minimal changes; just ensure it works with the new `Cli` struct instead of `ArgMatches`

#### 14. Verify compilation and test
- `cargo check` after each module migration
- `cargo clippy` for lint issues
- Run existing tests / integration tests
- Verify `--help` output for all subcommand groups

---

## Final File Structure

```
client/src/
├── main.rs                    # Minimal: parse + dispatch
├── lib.rs                     # Cli struct definition
├── error.rs                   # CliError, CliResult types
├── utils.rs                   # Shared utilities (refactored)
├── community_spec.rs          # Community spec parsing (minor changes)
└── commands/
    ├── mod.rs                 # Commands enum + match_command()
    ├── account.rs             # new-account, list-accounts, export-secret
    ├── chain.rs               # balance, transfer, listen, metadata, treasury
    ├── community.rs           # new-community, add/remove locations, list
    ├── ceremonies.rs          # 16 ceremony commands
    ├── scheduler.rs           # get-phase, get-cindex, next-phase
    ├── bazaar.rs              # business & offering CRUD
    ├── faucet.rs              # faucet lifecycle
    ├── reputation.rs          # rings + commitments
    ├── democracy.rs           # proposals, voting, enactment
    ├── offline_payment.rs     # ZK proof generation & trusted setup
    └── ipfs.rs                # IPFS upload (or merge into community)
```

## Breaking Changes Summary

| Before | After |
|--------|-------|
| `encointer-client-notee transfer ...` | `encointer-client-notee transfer ...` (unchanged — flattened) |
| `encointer-client-notee register-participant ...` | `encointer-client-notee ceremony register ...` |
| `encointer-client-notee new-community ...` | `encointer-client-notee community new ...` |
| `encointer-client-notee create-business ...` | `encointer-client-notee bazaar create-business ...` |
| `encointer-client-notee get-phase` | `encointer-client-notee scheduler get-phase` |
| `encointer-client-notee create-faucet ...` | `encointer-client-notee faucet create ...` |
| `encointer-client-notee vote ...` | `encointer-client-notee democracy vote ...` |
| `encointer-client-notee generate-offline-payment ...` | `encointer-client-notee offline-payment generate ...` |

The most common operations (`balance`, `transfer`, `new-account`, `list-accounts`) stay at the top level via `#[command(flatten)]`. Domain-specific commands move under their group prefix, improving discoverability via `--help`.

## Key Design Decisions

1. **Derive over Builder**: All clap configuration via derive macros — declarative, type-safe, less boilerplate
2. **Flatten for frequent commands**: `Account` and `Chain` commands are flattened to top level for ergonomics
3. **`&Cli` passed everywhere**: Global config struct replaces string-keyed `ArgMatches` extraction
4. **Shared `Args` structs**: Common argument patterns (account, seed, CID) defined once as `#[derive(Args)]` and composed into command variants
5. **Async throughout**: All `run()` methods are `async fn` since most commands make RPC calls
6. **One module per group**: Simplifies navigation; the ceremony and offline-payment modules will still be large but are self-contained

## References

- [Encointer CLI (current)](https://github.com/encointer/encointer-node/tree/master/client)
- [Integritee CLI (reference pattern)](https://github.com/integritee-network/worker/tree/master/cli)
- [clap 4.5.x documentation](https://docs.rs/clap/latest/clap/)
- [clap derive tutorial](https://docs.rs/clap/latest/clap/_derive/_tutorial/index.html)

### PR DESCRIPTION
**Pull request by brenzi**
closes #423 

* major clap upgrade to nested subcommands

Attention!
* [x] release this and push dockers. and then
   * [ ] also update CI in [encointer parachain](https://github.com/encointer/encointer-parachain)
   * [x] update tutorials in [book](https://github.com/encointer/book)

## cli nesting

```
● encointer-cli [-u|--node-url] [-p|--node-port] [-c|--cid] [--tx-payment-cid] [--at] [-v|--verbose]                                                  
  ├── balance <account> [-a|--all]                                                                                                                  
  ├── transfer <from> <to> <amount> [-d|--dryrun]                                                                                                     
  ├── transfer-all <from> <to>                                                                                                                      
  ├── listen [-e|--await-events <N>] [-b|--await-blocks <N>]                                                                                          
  ├── print-metadata                                                                                                                                  
  ├── account
  │   ├── new [seed]
  │   ├── list
  │   ├── export <account>
  │   ├── fund <fundees...>
  │   ├── poseidon-commitment
  │   │   ├── register <account>
  │   │   └── get <account>
  │   └── bandersnatch-pubkey
  │       └── register <account> [--key <hex>]
  ├── community
  │   ├── new <specfile> [-s|--signer] [-d|--dryrun] [-w|--wrap-call] [--batch-size]
  │   ├── list
  │   ├── issuance
  │   ├── location
  │   │   ├── list
  │   │   ├── add <specfile> [-s|--signer] [-d|--dryrun]
  │   │   └── remove [-s|--signer] [-d|--dryrun] [-g|--geohash] [-l|--location-index]
  │   └── treasury
  │       ├── get-account
  │       └── swap-option
  │           ├── get-native <account>
  │           ├── get-asset <account>
  │           ├── exercise-native <account> <amount>
  │           └── exercise-asset <account> <amount>
  ├── ceremony
  │   ├── phase
  │   ├── index
  │   ├── participant
  │   │   ├── register <account> [-s|--signer]
  │   │   ├── unregister <account> [-s|--signer] [ceremony_index]
  │   │   ├── upgrade <account> [-s|--signer]
  │   │   ├── endorse <bootstrapper> -e|--endorsees <endorsees...>
  │   │   ├── attest <account> <attestees...>
  │   │   ├── new-claim <account> <vote>
  │   │   ├── claim-reward [-s|--signer] [--meetup-index] [-a|--all]
  │   │   ├── list [ceremony_index]
  │   │   ├── reputation <account>
  │   │   └── proof-of-attendance <account> [--ceremony-index]
  │   ├── list-meetups [ceremony_index]
  │   ├── list-attestees [ceremony_index]
  │   ├── list-reputables
  │   ├── stats [--ceremony-index]
  │   └── admin
  │       ├── next-phase [-s|--signer]
  │       ├── bootstrapper-tickets
  │       ├── purge <from_cindex> <to_cindex>
  │       └── set-meetup-time-offset --time-offset <ms>
  ├── democracy
  │   ├── propose
  │   │   ├── set-inactivity-timeout <account> <inactivity_timeout>
  │   │   ├── update-nominal-income <account> <nominal_income>
  │   │   ├── update-demurrage <account> <demurrage_halving_blocks>
  │   │   ├── petition <account> <demand>
  │   │   ├── spend-native <account> <to> <amount>
  │   │   ├── issue-swap-native-option <account> <to> --native-allowance [--rate] [--do-burn] [--valid-from] [--valid-until]
  │   │   └── issue-swap-asset-option <account> <to> --asset-id --asset-allowance [--rate] [--do-burn] [--valid-from] [--valid-until]
  │   ├── proposal
  │   │   ├── list [-a|--all]
  │   │   └── update-state <account> <proposal_id>
  │   ├── enactment-queue
  │   └── vote <account> <proposal_id> <vote> <reputation_vec>
  ├── bazaar
  │   ├── business
  │   │   ├── create <account> --ipfs-cid
  │   │   ├── update <account> --ipfs-cid
  │   │   ├── list
  │   │   └── offerings <account>
  │   └── offering
  │       ├── create <account> --ipfs-cid
  │       └── list
  ├── faucet
  │   ├── create <account> <faucet_name> <faucet_balance> <faucet_drip_amount> <whitelist...>
  │   ├── drip <account> <faucet_account> <cindex>
  │   ├── dissolve [-s|--signer] <faucet_account> <faucet_beneficiary>
  │   ├── close <account> <faucet_account>
  │   ├── set-reserve-amount [-s|--signer] <faucet_reserve_amount>
  │   └── list
  ├── personhood
  │   ├── ring
  │   │   ├── initiate <account> --ceremony-index
  │   │   ├── continue <account>
  │   │   └── get --ceremony-index
  │   ├── prove-ring-membership <account> --ceremony-index [--level] [--sub-ring]
  │   ├── verify-ring-membership --signature --ceremony-index [--level] [--sub-ring]
  │   └── commitment
  │       ├── list [--purpose-id]
  │       └── purposes
  ├── offline-payment
  │   ├── pay [-s|--signer] --to --amount [--pk-file]
  │   ├── settle [-s|--signer] [--proof-file] [--proof] [--sender] [--recipient] [--amount] [--nullifier]
  │   └── admin
  │       ├── set-vk [-s|--signer] [--vk-file] [--vk]
  │       ├── generate-test-vk
  │       ├── trusted-setup
  │       │   ├── generate [--pk-out] [--vk-out]
  │       │   └── verify --pk --vk
  │       ├── ceremony
  │       │   ├── init [--pk-out] [--transcript]
  │       │   ├── contribute [--pk] [--transcript] --participant
  │       │   ├── verify [--pk] [--transcript]
  │       │   └── finalize [--pk] [--pk-out] [--vk-out]
  │       └── inspect-key --file
  └── ipfs
      └── upload [-s|--signer] [--gateway] <file_path>
```

## crate naming
```
Crate renames:                                                                                                                                            
   
  ┌────────────────────────────────────────┬────────────────────────┐                                                                                       
  │                Current                 │          New           │
  ├────────────────────────────────────────┼────────────────────────┤
  │ encointer-node-notee (package)         │ encointer-node         │
  ├────────────────────────────────────────┼────────────────────────┤
  │ encointer-client-notee (package)       │ encointer-cli          │
  ├────────────────────────────────────────┼────────────────────────┤
  │ encointer-node-notee-runtime (package) │ encointer-node-runtime │
  └────────────────────────────────────────┴────────────────────────┘

  Binary names:

  ┌─────────────────────────────────┬───────────────────────────────────────────────────────────────┐
  │             Current             │                              New                              │
  ├─────────────────────────────────┼───────────────────────────────────────────────────────────────┤
  │ encointer-node-notee            │ encointer-node                                                │
  ├─────────────────────────────────┼───────────────────────────────────────────────────────────────┤
  │ encointer-client-notee          │ encointer-cli                                                 │
  └─────────────────────────────────┴───────────────────────────────────────────────────────────────┘

```

### CODE REVIEW

File: client/src/commands/mod.rs [hunk 1]
```diff
@@ -12,3 +12,331 @@ pub mod encointer_scheduler;
 pub mod encointer_treasuries;
```
Comment (clangenb) [inline client/src/commands/mod.rs]: I guess I would split this into multiple files, but I do not have a strong opinion.

File: client/src/commands/mod.rs [hunk 2]
```diff
@@ -12,3 +12,331 @@ pub mod encointer_scheduler;
...
+
+use crate::cli::{
+	BazaarCmd, CeremonyCmd, ChainCmd, Cli, Commands, CommunityCmd, DemocracyCmd, FaucetCmd,
+	IpfsCmd, OfflinePaymentCmd, ReputationCmd,
+};
+
+pub async fn run(cli: &Cli) {
+	match &cli.command {
+		Commands::Account(cmd) => match cmd {
+			crate::cli::AccountCmd::NewAccount { seed } => keystore::new_account(seed.as_deref()),
```
Comment (clangenb) [inline client/src/commands/mod.rs]: I think this pattern is easier:

```rust
Commands::Account(cmd) => cmd.run(cli)
```

**Review by clangenb — COMMENTED** [review]
Finally, doomsday for Clap's old style has come! 🥳 

From a medium level perspective, it looks very good. I only have one comment regarding the forwarding of the CLI cmds.

File: client/src/commands/mod.rs (hunk 1 above)
Comment (brenzi) [reply client/src/commands/mod.rs]: I was wondering too. But refactoring behind the scene doesn't break anything, so we can reconsider later

File: client/src/commands/mod.rs (hunk 2 above)
Comment (clangenb) [reply client/src/commands/mod.rs]: Not sure if `cli` is needed in the run.

Comment (brenzi) [reply client/src/commands/mod.rs]: done
