### PR TITLE
fix try runtime

### LINKED ISSUE #340: [CI] should build with try-runtime and runtime-benchmark features as well
currently not tested  (and not working)

### PR DESCRIPTION
**Pull request by brenzi**
closes #340

..and fixes errors in respective build

### CODE REVIEW

File: node/src/command.rs [hunk 1]
```diff
@@ -26,6 +26,7 @@ use frame_benchmarking_cli::{BenchmarkCmd, ExtrinsicFactory, SUBSTRATE_REFERENCE
 use sc_cli::{ChainSpec, RuntimeVersion, SubstrateCli};
 use sc_service::PartialComponents;
 use sp_keyring::Sr25519Keyring;
+use try_runtime_cli::block_building_info::timestamp_with_aura_info;
```
Comment (clangenb) [inline node/src/command.rs:31]: needs to be feature gated

**Review by clangenb — APPROVED** [review]
One minor thing which breaks the build, but looks good to me otherwise

File: node/src/command.rs (hunk 1 above)
Comment (clangenb) [reply node/src/command.rs:31]: fixed it myself
